authorization:
  cloud_provider: 
    - azure

  resource_group:
    - skydentity
  
  actions:
    - CREATE

  roles:
    - restricted_role:
      - role: Microsoft.Storage/storageAccounts/blobServices/generateUserDelegationKey/action
      - scope: storage_account
      - object: /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/skydentity/providers/Microsoft.Storage/storageAccounts/skydentity
    - restricted_role:
      - role: Microsoft.Storage/storageAccounts/blobServices/write
      - scope: container
      - object: test_container_signedurl
    - restricted_role:
      - role: Microsoft.Storage/storageAccounts/blobServices/read
      - scope: container
      - object: test_container_signedurl
