authorization:
  cloud_provider: 
    - Azure

  resource_group:
    - skydentity
  
  actions:
    - CREATE

  region: 
    - westus

  roles:
    - restricted_role:
      - role: Microsoft.Storage/storageAccounts/blobServices/generateUserDelegationKey/action
      - scope: container
      - object: skydentity
    - restricted_role:
      - role: Microsoft.Storage/storageAccounts/blobServices/write
      - scope: container
      - object: skydentity
    - restricted_role:
      - role: Microsoft.Storage/storageAccounts/blobServices/read
      - scope: container
      - object: skydentity