virtual_machine:
  actions:
  - ALL
  allowed_images:
  - azure:
    - Canonical:0001-com-ubuntu-server
    - jammy-22-04-lts-gen2:latest
  attached_authorizations:
  - azure:
    - authorization:
      - F9508cac64568c588
  cloud_provider:
  - azure
  instance_type:
  - azure:
    - Standard_B1s
  regions:
  - azure:
    - eastus
    - westus
