virtual_machine:
  cloud_provider: 
    - azure
  
  actions:
    - ALL

  regions:
    - azure:
        - eastus
        - westus

  instance_type:
    - azure:
      - Standard_B1s

  allowed_images:
    - azure:
      - Canonical:0001-com-ubuntu-server \
        - jammy-22-04-lts-gen2:latest

# TODO  allowed_setup:

attached_authorizations:
  - azure:
      authorization:
        # Managed identities in Azure can be referred to by 
        - skypilot
