virtual_machine:
  cloud_provider: 
    - gcp
    - azure
  
  actions:
    - ALL

  regions:
    - gcp:
        - us-central1
        - us-east1
    - azure:
        - eastus
        - westus

  # Can specify max hardware spec or a list of allowed machines
  instance_type:
    - gcp:
      - n1-standard-1
      - n1-standard-2
    - azure:
      - max_spec:
        - max_cpu: 8
        - max_memory: 16
        - max_disk_size: 100
        - gpu: false

  allowed_images:
    - gcp:
      - ubuntu-1604-xenial-v20181029
      - ubuntu-1804-bionic-v20181029
    - azure:
      - Canonical:0001-com-ubuntu-server \
        - jammy-22-04-lts-gen2:latest

# TODO  allowed_setup:

attached_policies:
  - gcp:
      authorization:
        - service_account_x created from a previous step
  - azure:
      authorization:
        - managed identity created from a previous step
