virtual_machine:
  actions:
  - ALL
  allowed_images:
  - azure:
    - ubuntu-hpc:2204
  cloud_provider:
  - azure
  instance_type:
  - azure:
    - Standard_B1ms
  regions:
  - azure:
    - westus
  startup_scripts:
      - azure:
        # Hash of skypilot setup script
        - e6579aeaa32fdc6fcd94cc6c044c0e486d794d7c1c3d516386c137130099113d

  attached_authorizations:
  - azure:
    - authorization:
      - placeholder

reads:
  azure:
    resource_group: skydentity-e318-westus

    regions:
    - westus

    virtualMachines: true
    virtualMachineInstanceView: true
    networkInterfaces: true
    ipAddresses: true
    operations: true
    virtualNetworks: true
    subnets: true
    networkSecurityGroups: true
    deployments: true