storage:
  cloud_provider:
    - GCP

  project:
    - sky-identity

  actions:
    - READ
    - UPLOAD

  buckets:
    - skydentity-test-storage-1
    - skydentity-test-storage-2
    - skydentity-test-storage-3
    - skydentity-test-storage-4
    - skydentity-test-storage-5
    - skydentity-test-storage-6
    - skydentity-test-storage-7
    - skydentity-test-storage-8
    - skydentity-test-storage-9
    - skydentity-test-storage-10
    - skydentity-test-storage-11
    - skydentity-test-storage-12
    - skydentity-test-storage-13
    - skydentity-test-storage-14
    - skydentity-test-storage-15
    - skydentity-test-storage-16
    - skydentity-test-storage-17
    - skydentity-test-storage-18
    - skydentity-test-storage-19
    - skydentity-test-storage-20
    - skydentity-test-storage-21
    - skydentity-test-storage-22
    - skydentity-test-storage-23
    - skydentity-test-storage-24
    - skydentity-test-storage-25
    - skydentity-test-storage-26
    - skydentity-test-storage-27
    - skydentity-test-storage-28
    - skydentity-test-storage-29
    - skydentity-test-storage-30
