attached_authorizations:
- gcp:
  - authorization: F26ab702ebcc23400@sky-identity.iam.gserviceaccount.com
reads:
  gcp:
    firewalls: true
    operations: true
    project: sky-identity
    regions:
    - us-west1
    reservations: true
    subnetworks: true
    zones:
    - us-west1-b
virtual_machine:
  actions:
  - ALL
  allowed_images:
  - gcp:
    - debian-10-buster-v20240213
    - debian-10-buster-v20240110
    - ubuntu-1604-xenial-v20181029
    - ubuntu-1804-bionic-v20181029
    - ubuntu-2204-jammy-v20240223
  cloud_provider:
  - gcp
  instance_type:
  - gcp:
    - n1-standard-1
    - n1-standard-2
  regions:
  - gcp:
    - us-west1
    - us-west1-b
  startup_scripts:
  - gcp:
    - 2cc8351d05e4f5877b8c97ac73fd220b50c07729da55b089f4653aebac4efab6
