# syntax=docker/dockerfile:1

FROM python:3.9-slim-bullseye 

WORKDIR /skydentity-proxy

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY requirements.txt .
COPY certs/domain_dir ./certs
COPY app.py .
     
RUN pip3 install -r requirements.txt

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=5000", "--cert=certs/domain.crt", "--key=certs/domain.key"]
